version: '3.3'

services:
  web:
    build: . # папка, где находится Dockerfile сервиса web
    command: gunicorn classify_prk.wsgi:application --bind 0.0.0.0:8000  # Комманда, которая будет выполнена при запуске контейнера
    expose:
      - 8000 # порт 8000 открыт только внутри системы, для других служб Docker. Порт больше не будет публиковаться на хост-машине
    env_file:
      - ./.env.dev
    environment:
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}

  nginx:
    build: ./nginx
    ports:
      - 80:80
    environment:
      - SERVER_NAME=${SERVER_NAME}
    depends_on:
      - web
